citacoes = [
    "Podemos esquecer o que nos feriu, mas nunca esqueceremos o que nos uniu. — Pablo Neruda",
    "A luta continua, mas a vitória é certa. — Pablo Neruda",
    "Não há maior dor do que ver a dor de um povo. — Pablo Neruda",
    "A poesia é o eco da dor e da luta de um povo. — Pablo Neruda",
    "O mundo precisa de mais amor e menos poder. — Pablo Neruda",
    "Eu sou comunista porque sou amante da liberdade. — Pablo Neruda",
    "A revolução é o grito do povo, a expressão da sua luta. — Pablo Neruda",
    "Somos a geração do amanhã e o amanhã é nosso. — Pablo Neruda",
    "O capitalismo só cria miséria e desigualdade. — Pablo Neruda",
    "Não podemos ser neutros diante da injustiça. — Pablo Neruda",
    "O futuro só pode ser construído pela força do povo. — Pablo Neruda",
    "A revolução é poesia viva, é o amor de um povo em movimento. — Pablo Neruda",
    "A esperança é o último a morrer, mas a luta nunca deve cessar. — Pablo Neruda",
    "Não somos poetas, somos guerreiros do povo. — Pablo Neruda",
    "A revolução é feita de sonhos, mas também de sangue e suor. — Pablo Neruda",
    "O comunismo é a única maneira de garantir justiça social. — Pablo Neruda",
    "Para libertar o povo, devemos derrotar os opressores. — Pablo Neruda",
    "Eu canto a liberdade, a revolução e o amor. — Pablo Neruda",
    "A maior revolução é a que se faz dentro de nós. — Pablo Neruda",
    "O comunismo é a força da história que avança. — Pablo Neruda",
    "A revolução não é uma maçã que cai quando está madura. É preciso fazê-la cair. — Che Guevara",
    "Se você está em dificuldades e não tem solução, enfrente a luta. — Che Guevara",
    "A guerra é um processo contínuo até a vitória total. — Che Guevara",
    "A revolução é uma luta de todos, mas a vitória é do povo. — Che Guevara",
    "A verdadeira luta de classes não é apenas política, mas também ideológica. — Che Guevara",
    "Não há luta sem sacrifícios. — Che Guevara",
    "Os revolucionários não são seres especiais, mas homens comuns que fazem o que é necessário. — Che Guevara",
    "Se o presente é de luta, o futuro será de vitória. — Che Guevara",
    "A revolução é feita por um povo consciente de sua força. — Che Guevara",
    "A única luta que se perde é a que se abandona. — Che Guevara",
    "Se o capitalismo cria pobreza, a revolução cria prosperidade. — Che Guevara",
    "O futuro do socialismo depende da nossa capacidade de organizar. — Che Guevara",
    "A luta armada é uma expressão do povo que quer ser livre. — Che Guevara",
    "O medo é o principal inimigo da revolução. — Che Guevara",
    "A paz não é ausência de guerra, é a luta pela justiça. — Che Guevara",
    "Em cada revolução, o povo é a força que vence. — Che Guevara",
    "A classe trabalhadora deve estar preparada para o sacrifício, pois o socialismo exige isso. — Che Guevara",
    "As massas são a chave para a vitória de qualquer revolução. — Che Guevara",
    "A liberdade é conquistada com a luta. — Che Guevara",
    "A revolução é um processo contínuo, em constante movimento. — Che Guevara",
    "A única maneira de combater a opressão é com a revolução. — Che Guevara",
    "Todo revolucionário é um guerrilheiro de coração. — Che Guevara",
    "A vitória do povo é a vitória de todos. — Che Guevara",
    "Nada é impossível quando o povo se une. — Che Guevara",
    "O capitalismo está condenado a cair, pois é insustentável. — Che Guevara",
    "A guerra não é um fim, mas um meio de alcançar a justiça. — Che Guevara",
    "É preciso vencer para que o povo se liberte. — Che Guevara",
    "A luta revolucionária não tem fim. — Che Guevara",
    "Se você luta por uma causa justa, a vitória será sua. — Che Guevara",
    "A revolução é como uma flor; precisa de tempo para crescer. — Fidel Castro",
    "A luta pela liberdade é eterna. — Fidel Castro",
    "Não há conquista sem sacrifício. — Fidel Castro",
    "A única revolução possível é a que parte do povo. — Fidel Castro",
    "O povo é o verdadeiro motor da revolução. — Fidel Castro",
    "A solidariedade internacional é o único caminho para a liberdade. — Fidel Castro",
    "O socialismo não é uma escolha, é uma necessidade. — Fidel Castro",
    "A revolução se faz a cada dia, no trabalho e na luta. — Fidel Castro",
    "É preciso criar uma nova sociedade, sem opressores. — Fidel Castro",
    "A liberdade do povo não tem preço, só se conquista com a luta. — Fidel Castro",
    "Cada dia sem revolução é um dia perdido. — Fidel Castro",
    "A vitória da revolução não é uma questão de sorte, mas de organização. — Fidel Castro",
    "O imperialismo sempre tenta destruir as revoluções populares. — Fidel Castro",
    "A revolução cubana é a esperança de um mundo mais justo. — Fidel Castro",
    "Nada mais poderoso que a união do povo. — Fidel Castro",
    "A revolução exige coragem e perseverança. — Fidel Castro",
    "A política externa deve servir aos interesses do povo. — Fidel Castro",
    "Não há espaço para a dúvida na luta revolucionária. — Fidel Castro",
    "A revolução começa com a consciência do povo. — Fidel Castro",
    "O poder está nas mãos do povo, não dos imperialistas. — Fidel Castro",
    "A educação revolucionária é a chave para a mudança. — Fidel Castro",
    "A revolução é feita na rua e no coração do povo. — Fidel Castro",
    "O povo unido jamais será vencido. — Fidel Castro",
    "Nada é impossível para os que acreditam na luta. — Fidel Castro",
    "A vitória revolucionária é de todos. — Fidel Castro",
    "A revolução não é uma ideia, é uma prática. — Mao Zedong",
    "A revolução é o resultado de uma luta permanente. — Mao Zedong",
    "A força do povo é imbatível quando se organiza. — Mao Zedong",
    "Sem luta, não há vitória. — Mao Zedong",
    "O imperialismo deve ser derrotado, não importa o custo. — Mao Zedong",
    "A revolução é feita com as mãos sujas de suor e sangue. — Mao Zedong",
    "A revolução não se espera, se faz! — Mao Zedong",
    "A arte revolucionária é aquela que se compromete com o povo. — Mao Zedong",
    "As armas não são a única resposta, mas são uma resposta necessária. — Mao Zedong",
    "O socialismo é a chave para o futuro do mundo. — Mao Zedong",
    "O trabalhador é a espinha dorsal da revolução. — Mao Zedong",
    "Não há liberdade sem revolução. — Ho Chi Minh",
    "A liberdade do povo é a maior das vitórias. — Ho Chi Minh",
    "A revolução nunca é em vão. — Ho Chi Minh",
    "O povo é o verdadeiro poder. — Ho Chi Minh",
    "Sem unidade popular, não há revolução. — Ho Chi Minh",
    "O imperialismo deve ser derrotado, não importa o custo. — Ho Chi Minh",
    "A luta pela liberdade é contínua. — Ho Chi Minh",
    "O socialismo é o único caminho para a justiça. — Ho Chi Minh",
    "A revolução é permanente. — Ho Chi Minh",
    "A verdadeira luta é a luta pela liberdade do povo. — Ho Chi Minh",
    "O império nunca vencerá o povo unido. — Ho Chi Minh",
    "A opressão só termina com a revolução. — Ho Chi Minh",
    "A vitória do povo é inevitável. — Ho Chi Minh",
    "A luta nunca é em vão. — Ho Chi Minh",
    "O socialismo é o único caminho para a igualdade real. — Ho Chi Minh",
    "A revolução é feita na rua e no coração do povo. — Ho Chi Minh",
    "O povo unido jamais será vencido. — Ho Chi Minh",
    "Nada é impossível para os que acreditam na luta. — Ho Chi Minh",
    "A vitória revolucionária é de todos. — Ho Chi Minh"
]

prompt = '''
Faça uma matéria jornalística, simples e objetiva, sobre a aprovação de Propositura pela Câmara Municipal de Mogi das Cruzes. 
O texto deve ser formatado em parágrafos e não precisa iniciar com o local e data. No texto deve ter o partido dos
vereadores após o nome, entre parêteses, na primeira aparição. O texto deve obrigatoriamente ter o número do Requerimento,
Moção ou Projeto de Lei. Também é importante observar quando a proposta te mais de um autor, para citá-los como autores corretamente.
Pode variar o estilo e as ordens da estrutura sujeito, verbo e complemento, para deixar o texto mais dinâmico. É importante sempre variar o estilo do texto de uma geração para outra.
Também é interessante pegar algum trecho do projeto e colocar como aspas do autor ou dos autores. Mas só colocar como aspass
parte do texto de forma fidedigna, não inventar nada. O texto deve ser totalmente e fidedignamente baseado nas seguintes informações: 

'''